make: report correct dir when lib/.build is present
Now correctly shows
ERROR: build already in progress? (or remove /src/svtplay-dl/lib/.build/)
instead of
ERROR: build already in progress? (or remove /src/svtplay-dl/.build/)

Makes it easier to find the culprit. ;)